/**
 * Canonical REST catalog for the backend team.
 * All paths are relative to {NEXT_PUBLIC_API_BASE_URL}/v1
 */

export const ENDPOINT_CATALOG = [
  // Auth
  { method: "POST", path: "/auth/login", module: "auth", notes: "Public; authenticate a verified global user" },
  { method: "POST", path: "/auth/refresh-token", module: "auth", notes: "Bearer refreshToken" },
  { method: "POST", path: "/auth/email-verification/resend", module: "auth", notes: "Public; request or resend verification email" },
  { method: "POST", path: "/auth/email-verification/verify", module: "auth", notes: "Public; verify email with purpose-limited token" },
  { method: "POST", path: "/auth/forgot-password", module: "auth", notes: "Public; request password reset without revealing account existence" },
  { method: "POST", path: "/auth/reset-password", module: "auth", notes: "Public; reset password with one-time token" },
  { method: "GET", path: "/auth/me", module: "auth" },
  { method: "GET", path: "/auth/sessions", module: "auth" },
  { method: "DELETE", path: "/auth/sessions/:id", module: "auth" },
  { method: "POST", path: "/auth/workspace", module: "auth", notes: "Select workspace; returns scoped access token" },
  { method: "POST", path: "/auth/logout", module: "auth" },
  { method: "POST", path: "/auth/logout-all", module: "auth" },
  { method: "GET", path: "/user/profile", module: "user", notes: "Get current user profile" },
  { method: "PUT", path: "/user", module: "user", notes: "Update current user profile" },
  {
    method: "POST",
    path: "/workspaces/invitations/accept",
    module: "workspace-invitations",
    notes: "Public; accept a one-time workspace invitation",
  },

  // Workspace members (JWT; workspace-scoped)
  {
    method: "GET",
    path: "/workspaces/:workspaceId/members",
    module: "workspace-members",
    notes: "List workspace members",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/members-summary",
    module: "workspace-members",
    notes: "Joined, pending, and role totals",
  },
  {
    method: "POST",
    path: "/workspaces/:workspaceId/members",
    module: "workspace-members",
    notes: "Invite a user to the workspace",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/members/:memberId",
    module: "workspace-members",
  },
  {
    method: "PATCH",
    path: "/workspaces/:workspaceId/members/:memberId",
    module: "workspace-members",
    notes: "Accept invitation or update member role",
  },
  {
    method: "DELETE",
    path: "/workspaces/:workspaceId/members/:memberId",
    module: "workspace-members",
    notes: "Remove a member from the workspace",
  },
  {
    method: "DELETE",
    path: "/workspaces/:workspaceId/members/:memberId/invitation",
    module: "workspace-members",
    notes: "Cancel a pending workspace invitation",
  },
  {
    method: "POST",
    path: "/workspaces/:workspaceId/members/:memberId/invitation/resend",
    module: "workspace-members",
    notes: "Invalidate and resend a pending invitation",
  },
  {
    method: "POST",
    path: "/workspaces/:workspaceId/ownership-transfer",
    module: "workspace-members",
    notes: "Transfer workspace ownership to a joined member",
  },
  {
    method: "POST",
    path: "/workspaces/:workspaceId/members/import",
    module: "workspace-members",
    notes: "Bulk invite or add workspace users",
  },

  // Workspace operations (JWT; workspace-scoped)
  {
    method: "GET",
    path: "/workspaces/:workspaceId/profile",
    module: "workspace-operations",
    notes: "Profile, status, plan, limits, usage, locale, checklist",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/members-admin",
    module: "workspace-operations",
    notes: "Search and paginate members and invitations",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/members/me/preferences",
    module: "workspace-operations",
  },
  {
    method: "PATCH",
    path: "/workspaces/:workspaceId/members/me/preferences",
    module: "workspace-operations",
  },
  {
    method: "POST",
    path: "/workspaces/:workspaceId/members/leave",
    module: "workspace-operations",
    notes: "Leave after record reassignment",
  },
  {
    method: "POST",
    path: "/workspaces/:workspaceId/members/:memberId/deactivate",
    module: "workspace-operations",
  },
  {
    method: "POST",
    path: "/workspaces/:workspaceId/members/:memberId/activate",
    module: "workspace-operations",
  },

  // Workspaces (JWT)
  {
    method: "GET",
    path: "/workspaces/mine",
    module: "workspaces",
    notes: "List workspaces for the current user",
  },
  {
    method: "POST",
    path: "/workspaces",
    module: "workspaces",
    notes: "Create a workspace",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId",
    module: "workspaces",
  },
  {
    method: "PATCH",
    path: "/workspaces/:workspaceId",
    module: "workspaces",
  },
  {
    method: "DELETE",
    path: "/workspaces/:workspaceId",
    module: "workspaces",
    notes: "Soft-delete a workspace",
  },

  // Leads
  { method: "GET", path: "/leads/kanban", module: "leads", notes: "Kanban columns grouped by CRM status" },
  { method: "GET", path: "/leads", module: "leads", notes: "Paginated list" },
  { method: "GET", path: "/leads/:id", module: "leads" },
  { method: "POST", path: "/leads", module: "leads" },
  { method: "PATCH", path: "/leads/:id", module: "leads" },
  { method: "PATCH", path: "/leads/:id/owner", module: "leads" },
  { method: "DELETE", path: "/leads/:id/owner", module: "leads" },
  { method: "PATCH", path: "/leads/:id/company", module: "leads" },
  { method: "DELETE", path: "/leads/:id/company", module: "leads" },
  { method: "PATCH", path: "/leads/:id/status", module: "leads" },
  { method: "PATCH", path: "/leads/:id/lifecycle-stage", module: "leads" },
  { method: "PATCH", path: "/leads/:id/rating", module: "leads" },
  { method: "PATCH", path: "/leads/:id/score", module: "leads" },
  { method: "POST", path: "/leads/bulk", module: "leads" },
  { method: "POST", path: "/leads/import", module: "leads", notes: "JSON rows, max 100" },
  { method: "POST", path: "/leads/import/ads", module: "leads", notes: "Mapped ads rows until network pull exists" },
  { method: "POST", path: "/leads/import/sheets", module: "leads", notes: "Mapped sheet rows until Google OAuth exists" },
  { method: "GET", path: "/leads/:id/conversations", module: "leads" },
  { method: "POST", path: "/leads/:id/conversations", module: "leads", notes: "SMS/WhatsApp via Twilio when configured" },
  { method: "GET", path: "/leads/:id/credit-report", module: "leads" },
  { method: "POST", path: "/leads/:id/credit-report/refresh", module: "leads" },
  { method: "PATCH", path: "/leads/:id/pipeline-stage", module: "leads" },
  { method: "PUT", path: "/leads/:id/tags", module: "leads" },
  { method: "PUT", path: "/leads/:id/followers", module: "leads" },
  { method: "POST", path: "/leads/:id/followers", module: "leads" },
  { method: "POST", path: "/leads/:id/followers/:userId", module: "leads" },
  { method: "DELETE", path: "/leads/:id/followers/:userId", module: "leads" },
  { method: "GET", path: "/leads/:id/mortgage", module: "leads" },
  { method: "PUT", path: "/leads/:id/mortgage", module: "leads" },
  { method: "POST", path: "/leads/:id/convert", module: "leads", notes: "Requires existing contact/deal/company UUID" },
  { method: "DELETE", path: "/leads/:id", module: "leads", notes: "Soft-delete → recycle bin" },

  // Contacts (JWT; workspace via token claim)
  { method: "GET", path: "/contacts/board", module: "contacts" },
  { method: "GET", path: "/contacts", module: "contacts", notes: "Paginated list" },
  { method: "GET", path: "/contacts/:id", module: "contacts" },
  { method: "POST", path: "/contacts", module: "contacts" },
  { method: "PATCH", path: "/contacts/:id", module: "contacts" },
  { method: "DELETE", path: "/contacts/:id", module: "contacts", notes: "Soft-delete → recycle bin" },
  { method: "POST", path: "/contacts/import", module: "contacts", notes: "CSV / Excel / Sheets" },
  { method: "POST", path: "/contacts/bulk", module: "contacts", notes: "Assign, status, or soft-delete" },
  { method: "POST", path: "/contacts/:id/merge", module: "contacts", notes: "Merge source into survivor" },
  { method: "PUT", path: "/contacts/:id/tags", module: "contacts" },
  { method: "GET", path: "/contacts/:id/deals", module: "contacts" },
  { method: "GET", path: "/contacts/:id/tickets", module: "contacts" },

  // Companies (JWT; workspace via token claim)
  { method: "GET", path: "/companies", module: "companies", notes: "List workspace companies" },
  { method: "GET", path: "/companies/:id", module: "companies" },
  { method: "POST", path: "/companies", module: "companies" },
  { method: "PATCH", path: "/companies/:id", module: "companies" },
  { method: "DELETE", path: "/companies/:id", module: "companies", notes: "Soft-delete → recycle bin" },
  { method: "POST", path: "/companies/bulk", module: "companies", notes: "Bounded atomic bulk ops" },
  { method: "POST", path: "/companies/import", module: "companies", notes: "Queue JSON import" },
  { method: "POST", path: "/companies/export", module: "companies", notes: "Queue export task" },
  { method: "POST", path: "/companies/:id/merge", module: "companies", notes: "Merge source into survivor" },
  {
    method: "GET",
    path: "/companies/transfers/:transferId",
    module: "companies",
    notes: "Transfer job status",
  },

  // Estimates (JWT; workspace via token claim)
  { method: "GET", path: "/estimates", module: "estimates", notes: "Paginated list" },
  { method: "GET", path: "/estimates/:id", module: "estimates" },
  { method: "POST", path: "/estimates", module: "estimates" },
  { method: "PATCH", path: "/estimates/:id", module: "estimates" },
  { method: "DELETE", path: "/estimates/:id", module: "estimates", notes: "Soft-delete" },
  { method: "POST", path: "/estimates/:id/send", module: "estimates" },
  { method: "GET", path: "/estimates/:id/pdf", module: "estimates" },
  { method: "GET", path: "/estimates/:id/public-link", module: "estimates" },
  { method: "GET", path: "/estimates/:id/attachments", module: "estimates" },
  { method: "POST", path: "/estimates/:id/attachments", module: "estimates", notes: "multipart file" },
  {
    method: "DELETE",
    path: "/estimates/:id/attachments/:attachmentId",
    module: "estimates",
  },

  // Quotes (JWT; workspace via token claim)
  { method: "GET", path: "/quotes", module: "quotes", notes: "List quotes" },
  { method: "GET", path: "/quotes/:id", module: "quotes" },
  { method: "POST", path: "/quotes", module: "quotes" },
  { method: "PATCH", path: "/quotes/:id", module: "quotes" },
  { method: "DELETE", path: "/quotes/:id", module: "quotes", notes: "Soft-delete" },
  { method: "POST", path: "/quotes/:id/send", module: "quotes" },
  { method: "GET", path: "/quotes/:id/pdf", module: "quotes" },
  { method: "GET", path: "/quotes/:id/public-link", module: "quotes" },
  { method: "GET", path: "/quotes/:id/attachments", module: "quotes" },
  { method: "POST", path: "/quotes/:id/attachments", module: "quotes", notes: "multipart file" },
  {
    method: "DELETE",
    path: "/quotes/:id/attachments/:attachmentId",
    module: "quotes",
  },

  // Invoices (JWT; workspace via token claim)
  { method: "GET", path: "/invoices", module: "invoices", notes: "Paginated list" },
  { method: "GET", path: "/invoices/:id", module: "invoices" },
  { method: "POST", path: "/invoices", module: "invoices" },
  { method: "PATCH", path: "/invoices/:id", module: "invoices" },
  { method: "DELETE", path: "/invoices/:id", module: "invoices", notes: "Soft-delete" },
  { method: "POST", path: "/invoices/:id/send", module: "invoices" },
  { method: "GET", path: "/invoices/:id/pdf", module: "invoices" },
  { method: "GET", path: "/invoices/:id/public-link", module: "invoices" },
  { method: "GET", path: "/invoices/:id/attachments", module: "invoices" },
  { method: "POST", path: "/invoices/:id/attachments", module: "invoices", notes: "multipart file" },
  {
    method: "DELETE",
    path: "/invoices/:id/attachments/:attachmentId",
    module: "invoices",
  },
  {
    method: "POST",
    path: "/invoices/:id/payments/stripe",
    module: "invoices",
    notes: "Stripe payment intent",
  },

  // Public sales documents (hash-gated; no JWT)
  { method: "GET", path: "/public/sales/quotes/:id/:hash", module: "public-sales", notes: "View quote via public link" },
  { method: "GET", path: "/public/sales/estimates/:id/:hash", module: "public-sales", notes: "View estimate via public link" },
  { method: "GET", path: "/public/sales/invoices/:id/:hash", module: "public-sales", notes: "View invoice via public link" },
  { method: "POST", path: "/public/sales/quotes/:id/:hash/accept", module: "public-sales", notes: "Accept quote via public link" },
  { method: "POST", path: "/public/sales/quotes/:id/:hash/decline", module: "public-sales", notes: "Decline quote via public link" },
  { method: "POST", path: "/public/sales/invoices/:id/:hash/pay-intent", module: "public-sales", notes: "Stripe payment intent for public invoice" },

  // Credit notes (JWT; workspace via token claim)
  { method: "GET", path: "/credit-notes", module: "credit-notes", notes: "Paginated list" },
  { method: "GET", path: "/credit-notes/:id", module: "credit-notes" },
  { method: "POST", path: "/credit-notes", module: "credit-notes" },
  { method: "PATCH", path: "/credit-notes/:id", module: "credit-notes" },
  { method: "DELETE", path: "/credit-notes/:id", module: "credit-notes", notes: "Soft-delete" },
  { method: "POST", path: "/credit-notes/:id/send", module: "credit-notes" },
  { method: "GET", path: "/credit-notes/:id/pdf", module: "credit-notes" },
  { method: "GET", path: "/credit-notes/:id/public-link", module: "credit-notes" },
  { method: "GET", path: "/credit-notes/:id/attachments", module: "credit-notes" },
  { method: "POST", path: "/credit-notes/:id/attachments", module: "credit-notes", notes: "multipart file" },
  {
    method: "DELETE",
    path: "/credit-notes/:id/attachments/:attachmentId",
    module: "credit-notes",
  },

  // Payments (JWT; workspace via token claim)
  { method: "GET", path: "/payments", module: "payments", notes: "List payments" },
  { method: "GET", path: "/payments/:id", module: "payments", notes: "Get payment by ID" },
  { method: "POST", path: "/payments", module: "payments", notes: "Record payment against invoice" },
  { method: "PATCH", path: "/payments/:id", module: "payments", notes: "Update payment" },
  { method: "DELETE", path: "/payments/:id", module: "payments", notes: "Refund a payment" },

  // Products & Services catalogue (JWT; workspace via token claim)
  { method: "GET", path: "/products", module: "products", notes: "List products / services" },
  { method: "GET", path: "/products/:id", module: "products", notes: "Get product by ID" },
  { method: "POST", path: "/products", module: "products", notes: "Create a product" },
  { method: "PATCH", path: "/products/:id", module: "products", notes: "Update a product" },
  { method: "DELETE", path: "/products/:id", module: "products", notes: "Soft-delete a product" },

  // Deals (JWT; workspace via token claim)
  { method: "GET", path: "/deals", module: "deals", notes: "List workspace deals" },
  { method: "GET", path: "/deals/pipeline", module: "deals", notes: "Stage cards + aggregates" },
  { method: "GET", path: "/deals/forecast", module: "deals" },
  { method: "GET", path: "/deals/:id", module: "deals" },
  { method: "POST", path: "/deals", module: "deals" },
  { method: "PATCH", path: "/deals/:id", module: "deals" },
  { method: "DELETE", path: "/deals/:id", module: "deals", notes: "Soft-delete" },
  { method: "POST", path: "/deals/bulk", module: "deals" },
  { method: "POST", path: "/deals/:id/restore", module: "deals" },
  { method: "POST", path: "/deals/:id/clone", module: "deals" },
  { method: "GET", path: "/deals/:id/contacts", module: "deals" },
  { method: "POST", path: "/deals/:id/contacts", module: "deals" },
  { method: "PUT", path: "/deals/:id/contacts", module: "deals" },
  { method: "PATCH", path: "/deals/:id/contacts/:contactId", module: "deals" },
  { method: "DELETE", path: "/deals/:id/contacts/:contactId", module: "deals" },

  // Tasks (JWT; workspace-scoped URL preferred when token has workspaceId)
  { method: "GET", path: "/tasks/board", module: "tasks", notes: "Local/remote adapter board" },
  { method: "GET", path: "/tasks", module: "tasks", notes: "Paginated list" },
  { method: "GET", path: "/tasks/today", module: "tasks", notes: "Due today UTC" },
  { method: "GET", path: "/tasks/upcoming", module: "tasks" },
  { method: "GET", path: "/tasks/overdue", module: "tasks" },
  { method: "GET", path: "/tasks/my", module: "tasks", notes: "Assigned to current member" },
  { method: "GET", path: "/tasks/:id", module: "tasks" },
  { method: "GET", path: "/tasks/:id/collaborators", module: "tasks" },
  { method: "POST", path: "/tasks", module: "tasks" },
  { method: "PATCH", path: "/tasks/:id", module: "tasks" },
  { method: "DELETE", path: "/tasks/:id", module: "tasks", notes: "Soft-delete" },
  { method: "POST", path: "/tasks/bulk", module: "tasks", notes: "Complete, reassign, or soft-delete" },
  { method: "POST", path: "/tasks/bulk-delete", module: "tasks" },
  { method: "POST", path: "/tasks/bulk-restore", module: "tasks" },
  { method: "POST", path: "/tasks/:id/restore", module: "tasks" },
  { method: "POST", path: "/tasks/:id/complete", module: "tasks" },
  { method: "POST", path: "/tasks/:id/reopen", module: "tasks" },
  { method: "POST", path: "/tasks/:id/cancel", module: "tasks" },
  { method: "POST", path: "/tasks/:id/duplicate", module: "tasks" },
  { method: "POST", path: "/tasks/:id/assignees/:userId", module: "tasks" },
  { method: "DELETE", path: "/tasks/:id/assignees/:userId", module: "tasks" },
  { method: "PUT", path: "/tasks/:id/assignees", module: "tasks" },
  { method: "POST", path: "/tasks/:id/collaborators/:userId", module: "tasks" },
  { method: "DELETE", path: "/tasks/:id/collaborators/:userId", module: "tasks" },
  { method: "PUT", path: "/tasks/:id/collaborators", module: "tasks" },
  { method: "PUT", path: "/tasks/:id/followers", module: "tasks" },
  { method: "POST", path: "/tasks/:id/tags", module: "tasks" },
  { method: "DELETE", path: "/tasks/:id/tags/:tagId", module: "tasks" },
  { method: "POST", path: "/tasks/:id/attachments", module: "tasks", notes: "Attach workspace storage object" },
  { method: "DELETE", path: "/tasks/:id/attachments/:attachmentId", module: "tasks" },
  { method: "GET", path: "/workspaces/:workspaceId/tasks", module: "tasks" },
  { method: "GET", path: "/workspaces/:workspaceId/tasks/today", module: "tasks" },
  { method: "GET", path: "/workspaces/:workspaceId/tasks/upcoming", module: "tasks" },
  { method: "GET", path: "/workspaces/:workspaceId/tasks/overdue", module: "tasks" },
  { method: "GET", path: "/workspaces/:workspaceId/tasks/my", module: "tasks" },
  { method: "GET", path: "/workspaces/:workspaceId/tasks/:id", module: "tasks" },
  { method: "GET", path: "/workspaces/:workspaceId/tasks/:id/collaborators", module: "tasks" },
  { method: "POST", path: "/workspaces/:workspaceId/tasks", module: "tasks" },
  { method: "PATCH", path: "/workspaces/:workspaceId/tasks/:id", module: "tasks" },
  { method: "DELETE", path: "/workspaces/:workspaceId/tasks/:id", module: "tasks" },
  { method: "POST", path: "/workspaces/:workspaceId/tasks/bulk", module: "tasks" },
  { method: "POST", path: "/workspaces/:workspaceId/tasks/bulk-delete", module: "tasks" },
  { method: "POST", path: "/workspaces/:workspaceId/tasks/bulk-restore", module: "tasks" },
  { method: "POST", path: "/workspaces/:workspaceId/tasks/:id/restore", module: "tasks" },
  { method: "POST", path: "/workspaces/:workspaceId/tasks/:id/complete", module: "tasks" },
  { method: "POST", path: "/workspaces/:workspaceId/tasks/:id/reopen", module: "tasks" },
  { method: "POST", path: "/workspaces/:workspaceId/tasks/:id/cancel", module: "tasks" },
  { method: "POST", path: "/workspaces/:workspaceId/tasks/:id/duplicate", module: "tasks" },
  { method: "POST", path: "/workspaces/:workspaceId/tasks/:id/assignees/:userId", module: "tasks" },
  { method: "DELETE", path: "/workspaces/:workspaceId/tasks/:id/assignees/:userId", module: "tasks" },
  { method: "PUT", path: "/workspaces/:workspaceId/tasks/:id/assignees", module: "tasks" },
  { method: "POST", path: "/workspaces/:workspaceId/tasks/:id/collaborators/:userId", module: "tasks" },
  { method: "DELETE", path: "/workspaces/:workspaceId/tasks/:id/collaborators/:userId", module: "tasks" },
  { method: "PUT", path: "/workspaces/:workspaceId/tasks/:id/collaborators", module: "tasks" },
  { method: "PUT", path: "/workspaces/:workspaceId/tasks/:id/followers", module: "tasks" },
  { method: "POST", path: "/workspaces/:workspaceId/tasks/:id/tags", module: "tasks" },
  { method: "DELETE", path: "/workspaces/:workspaceId/tasks/:id/tags/:tagId", module: "tasks" },
  { method: "POST", path: "/workspaces/:workspaceId/tasks/:id/attachments", module: "tasks" },
  { method: "DELETE", path: "/workspaces/:workspaceId/tasks/:id/attachments/:attachmentId", module: "tasks" },

  // Calls (workspace JWT preferred; lifecycle POSTs on /calls/:id/*)
  { method: "GET", path: "/calls", module: "calls", notes: "Paginated call list" },
  { method: "GET", path: "/calls/today", module: "calls", notes: "Scheduled today UTC" },
  { method: "GET", path: "/calls/completed", module: "calls" },
  { method: "GET", path: "/calls/missed", module: "calls" },
  { method: "GET", path: "/calls/my", module: "calls" },
  { method: "GET", path: "/calls/upcoming", module: "calls" },
  { method: "GET", path: "/calls/history", module: "calls" },
  { method: "GET", path: "/calls/:id", module: "calls" },
  { method: "POST", path: "/calls", module: "calls", notes: "Schedule or log a call" },
  { method: "PATCH", path: "/calls/:id", module: "calls" },
  { method: "DELETE", path: "/calls/:id", module: "calls", notes: "Soft-delete" },
  { method: "POST", path: "/calls/:id/start", module: "calls" },
  { method: "POST", path: "/calls/:id/dial", module: "calls", notes: "Twilio Voice outbound" },
  { method: "POST", path: "/calls/:id/complete", module: "calls" },
  { method: "POST", path: "/calls/:id/cancel", module: "calls" },
  { method: "POST", path: "/calls/:id/reschedule", module: "calls" },
  { method: "POST", path: "/calls/:id/log-outcome", module: "calls" },
  { method: "GET", path: "/workspaces/:workspaceId/calls", module: "calls" },
  { method: "GET", path: "/workspaces/:workspaceId/calls/today", module: "calls" },
  { method: "GET", path: "/workspaces/:workspaceId/calls/completed", module: "calls" },
  { method: "GET", path: "/workspaces/:workspaceId/calls/missed", module: "calls" },
  { method: "GET", path: "/workspaces/:workspaceId/calls/my", module: "calls" },
  { method: "GET", path: "/workspaces/:workspaceId/calls/upcoming", module: "calls" },
  { method: "GET", path: "/workspaces/:workspaceId/calls/history", module: "calls" },
  { method: "GET", path: "/workspaces/:workspaceId/calls/:id", module: "calls" },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/:relatedType/:relatedId/calls",
    module: "calls",
  },
  { method: "POST", path: "/workspaces/:workspaceId/calls", module: "calls" },
  { method: "PATCH", path: "/workspaces/:workspaceId/calls/:id", module: "calls" },
  { method: "DELETE", path: "/workspaces/:workspaceId/calls/:id", module: "calls" },
  { method: "POST", path: "/workspaces/:workspaceId/calls/:id/start", module: "calls" },
  { method: "POST", path: "/workspaces/:workspaceId/calls/:id/dial", module: "calls" },
  {
    method: "POST",
    path: "/workspaces/:workspaceId/calls/:id/complete",
    module: "calls",
  },
  { method: "POST", path: "/workspaces/:workspaceId/calls/:id/cancel", module: "calls" },
  {
    method: "POST",
    path: "/workspaces/:workspaceId/calls/:id/reschedule",
    module: "calls",
  },
  {
    method: "POST",
    path: "/workspaces/:workspaceId/calls/:id/log-outcome",
    module: "calls",
  },

  // Meetings (JWT; workspace-scoped URL preferred when token has workspaceId)
  { method: "GET", path: "/meetings", module: "meetings", notes: "Paginated list" },
  { method: "GET", path: "/meetings/upcoming", module: "meetings" },
  { method: "GET", path: "/meetings/:id", module: "meetings" },
  { method: "POST", path: "/meetings", module: "meetings" },
  { method: "PATCH", path: "/meetings/:id", module: "meetings" },
  { method: "DELETE", path: "/meetings/:id", module: "meetings", notes: "Soft-delete" },
  { method: "POST", path: "/meetings/:id/cancel", module: "meetings" },
  { method: "POST", path: "/meetings/:id/start", module: "meetings" },
  { method: "POST", path: "/meetings/:id/complete", module: "meetings" },
  { method: "POST", path: "/meetings/:id/reschedule", module: "meetings" },
  { method: "POST", path: "/meetings/:id/attendees/:userId", module: "meetings" },
  { method: "DELETE", path: "/meetings/:id/attendees/:userId", module: "meetings" },
  { method: "PUT", path: "/meetings/:id/attendees", module: "meetings" },
  { method: "POST", path: "/meetings/:id/reminders", module: "meetings" },
  { method: "GET", path: "/workspaces/:workspaceId/meetings", module: "meetings" },
  { method: "GET", path: "/workspaces/:workspaceId/meetings/upcoming", module: "meetings" },
  { method: "GET", path: "/workspaces/:workspaceId/meetings/:id", module: "meetings" },
  { method: "POST", path: "/workspaces/:workspaceId/meetings", module: "meetings" },
  { method: "PATCH", path: "/workspaces/:workspaceId/meetings/:id", module: "meetings" },
  { method: "DELETE", path: "/workspaces/:workspaceId/meetings/:id", module: "meetings" },
  { method: "POST", path: "/workspaces/:workspaceId/meetings/:id/cancel", module: "meetings" },
  { method: "POST", path: "/workspaces/:workspaceId/meetings/:id/start", module: "meetings" },
  { method: "POST", path: "/workspaces/:workspaceId/meetings/:id/complete", module: "meetings" },
  { method: "POST", path: "/workspaces/:workspaceId/meetings/:id/reschedule", module: "meetings" },
  {
    method: "POST",
    path: "/workspaces/:workspaceId/meetings/:id/attendees/:userId",
    module: "meetings",
  },
  {
    method: "DELETE",
    path: "/workspaces/:workspaceId/meetings/:id/attendees/:userId",
    module: "meetings",
  },
  { method: "PUT", path: "/workspaces/:workspaceId/meetings/:id/attendees", module: "meetings" },
  { method: "POST", path: "/workspaces/:workspaceId/meetings/:id/reminders", module: "meetings" },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/:relatedType/:relatedId/meetings",
    module: "meetings",
  },

  // CRM emails (JWT; workspace-scoped URL preferred when token has workspaceId)
  { method: "GET", path: "/emails", module: "emails", notes: "List CRM email activity" },
  { method: "GET", path: "/emails/:id", module: "emails" },
  { method: "POST", path: "/emails", module: "emails", notes: "Create draft" },
  { method: "PATCH", path: "/emails/:id", module: "emails", notes: "Edit draft" },
  { method: "DELETE", path: "/emails/:id", module: "emails", notes: "Soft-delete non-queued" },
  { method: "POST", path: "/emails/:id/send", module: "emails", notes: "Send or schedule" },
  { method: "POST", path: "/emails/:id/retry", module: "emails" },
  { method: "POST", path: "/emails/:id/cancel", module: "emails" },
  { method: "POST", path: "/emails/:id/apply-template", module: "emails" },
  { method: "POST", path: "/emails/:id/attachments", module: "emails", notes: "Attach workspace object" },
  { method: "DELETE", path: "/emails/:id/attachments/:attachmentId", module: "emails" },
  { method: "GET", path: "/emails/:id/attachments/:attachmentId/download", module: "emails" },
  { method: "GET", path: "/workspaces/:workspaceId/emails", module: "emails" },
  { method: "GET", path: "/workspaces/:workspaceId/emails/:id", module: "emails" },
  { method: "POST", path: "/workspaces/:workspaceId/emails", module: "emails" },
  { method: "PATCH", path: "/workspaces/:workspaceId/emails/:id", module: "emails" },
  { method: "DELETE", path: "/workspaces/:workspaceId/emails/:id", module: "emails" },
  { method: "POST", path: "/workspaces/:workspaceId/emails/:id/send", module: "emails" },
  { method: "POST", path: "/workspaces/:workspaceId/emails/:id/retry", module: "emails" },
  { method: "POST", path: "/workspaces/:workspaceId/emails/:id/cancel", module: "emails" },
  { method: "POST", path: "/workspaces/:workspaceId/emails/:id/apply-template", module: "emails" },
  { method: "POST", path: "/workspaces/:workspaceId/emails/:id/attachments", module: "emails" },
  {
    method: "DELETE",
    path: "/workspaces/:workspaceId/emails/:id/attachments/:attachmentId",
    module: "emails",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/emails/:id/attachments/:attachmentId/download",
    module: "emails",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/:relatedType/:relatedId/emails",
    module: "emails",
    notes: "Parent-scoped email activity",
  },

  // CRM messages (JWT; workspace-scoped URL preferred when token has workspaceId)
  { method: "GET", path: "/messages", module: "messages", notes: "List CRM messages" },
  { method: "GET", path: "/messages/all", module: "messages", notes: "List all visible CRM messages" },
  { method: "GET", path: "/messages/recent", module: "messages", notes: "Visible messages from the last 30 days" },
  { method: "GET", path: "/messages/unread", module: "messages", notes: "Unread internal messages for current member" },
  { method: "GET", path: "/messages/:id", module: "messages" },
  { method: "POST", path: "/messages", module: "messages", notes: "Create draft internal or external" },
  { method: "PATCH", path: "/messages/:id", module: "messages", notes: "Edit draft" },
  { method: "DELETE", path: "/messages/:id", module: "messages", notes: "Soft-delete non-queued" },
  { method: "POST", path: "/messages/:id/read", module: "messages", notes: "Mark an internal message read" },
  { method: "POST", path: "/messages/:id/unread", module: "messages", notes: "Mark an internal message unread" },
  { method: "POST", path: "/messages/:id/send", module: "messages", notes: "Queue idempotent delivery" },
  { method: "POST", path: "/messages/:id/retry", module: "messages" },
  { method: "POST", path: "/messages/:id/cancel", module: "messages", notes: "Cancel queued delivery" },
  { method: "POST", path: "/messages/:id/attachments", module: "messages", notes: "Attach workspace storage metadata" },
  { method: "DELETE", path: "/messages/:id/attachments/:attachmentId", module: "messages" },
  { method: "GET", path: "/messages/:id/attachments/:attachmentId/download", module: "messages" },
  { method: "GET", path: "/workspaces/:workspaceId/messages", module: "messages" },
  { method: "GET", path: "/workspaces/:workspaceId/messages/all", module: "messages" },
  { method: "GET", path: "/workspaces/:workspaceId/messages/recent", module: "messages" },
  { method: "GET", path: "/workspaces/:workspaceId/messages/unread", module: "messages" },
  { method: "GET", path: "/workspaces/:workspaceId/messages/:id", module: "messages" },
  { method: "POST", path: "/workspaces/:workspaceId/messages", module: "messages" },
  { method: "PATCH", path: "/workspaces/:workspaceId/messages/:id", module: "messages" },
  { method: "DELETE", path: "/workspaces/:workspaceId/messages/:id", module: "messages" },
  { method: "POST", path: "/workspaces/:workspaceId/messages/:id/read", module: "messages" },
  { method: "POST", path: "/workspaces/:workspaceId/messages/:id/unread", module: "messages" },
  { method: "POST", path: "/workspaces/:workspaceId/messages/:id/send", module: "messages" },
  { method: "POST", path: "/workspaces/:workspaceId/messages/:id/retry", module: "messages" },
  { method: "POST", path: "/workspaces/:workspaceId/messages/:id/cancel", module: "messages" },
  { method: "POST", path: "/workspaces/:workspaceId/messages/:id/attachments", module: "messages" },
  {
    method: "DELETE",
    path: "/workspaces/:workspaceId/messages/:id/attachments/:attachmentId",
    module: "messages",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/messages/:id/attachments/:attachmentId/download",
    module: "messages",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/:relatedType/:relatedId/messages",
    module: "messages",
    notes: "Parent-scoped message activity",
  },

  // CRM notes (JWT; workspace-scoped URL preferred when token has workspaceId)
  { method: "GET", path: "/notes", module: "notes", notes: "List readable workspace notes" },
  { method: "GET", path: "/notes/recent", module: "notes", notes: "Readable notes from the last 30 days" },
  { method: "GET", path: "/notes/my", module: "notes", notes: "Notes authored by the current member" },
  { method: "GET", path: "/notes/standalone", module: "notes", notes: "Standalone notes without a CRM parent" },
  { method: "GET", path: "/notes/by-category/:noteType", module: "notes", notes: "Notes in a note category" },
  { method: "GET", path: "/notes/:noteId", module: "notes" },
  { method: "POST", path: "/notes", module: "notes", notes: "Create note for a writable CRM record" },
  { method: "PATCH", path: "/notes/:noteId", module: "notes", notes: "Update authored or administered note" },
  { method: "DELETE", path: "/notes/:noteId", module: "notes", notes: "Soft-delete" },
  { method: "POST", path: "/notes/bulk-delete", module: "notes", notes: "Soft-delete up to 100 notes" },
  { method: "POST", path: "/notes/:noteId/restore", module: "notes" },
  { method: "GET", path: "/workspaces/:workspaceId/notes", module: "notes" },
  { method: "GET", path: "/workspaces/:workspaceId/notes/recent", module: "notes" },
  { method: "GET", path: "/workspaces/:workspaceId/notes/my", module: "notes" },
  { method: "GET", path: "/workspaces/:workspaceId/notes/standalone", module: "notes" },
  { method: "GET", path: "/workspaces/:workspaceId/notes/by-category/:noteType", module: "notes" },
  { method: "GET", path: "/workspaces/:workspaceId/notes/:noteId", module: "notes" },
  { method: "POST", path: "/workspaces/:workspaceId/notes", module: "notes" },
  { method: "PATCH", path: "/workspaces/:workspaceId/notes/:noteId", module: "notes" },
  { method: "DELETE", path: "/workspaces/:workspaceId/notes/:noteId", module: "notes" },
  { method: "POST", path: "/workspaces/:workspaceId/notes/bulk-delete", module: "notes" },
  { method: "POST", path: "/workspaces/:workspaceId/notes/:noteId/restore", module: "notes" },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/:relatedType/:relatedId/notes",
    module: "notes",
    notes: "Parent-scoped notes",
  },

  // Reminders (JWT; workspace-scoped URL preferred when token has workspaceId)
  { method: "GET", path: "/reminders", module: "reminders", notes: "List workspace reminders" },
  { method: "GET", path: "/reminders/my", module: "reminders", notes: "Reminders targeted to current user" },
  { method: "GET", path: "/reminders/upcoming", module: "reminders", notes: "Due in the next 30 days" },
  { method: "GET", path: "/reminders/overdue", module: "reminders" },
  { method: "GET", path: "/reminders/capabilities", module: "reminders" },
  { method: "GET", path: "/reminders/:id", module: "reminders" },
  { method: "POST", path: "/reminders", module: "reminders", notes: "Create and schedule" },
  { method: "PATCH", path: "/reminders/:id", module: "reminders" },
  { method: "DELETE", path: "/reminders/:id", module: "reminders", notes: "Dismiss" },
  { method: "POST", path: "/reminders/:id/snooze", module: "reminders" },
  { method: "POST", path: "/reminders/:id/reschedule", module: "reminders" },
  { method: "POST", path: "/reminders/:id/complete", module: "reminders" },
  { method: "POST", path: "/reminders/:id/cancel", module: "reminders" },
  { method: "GET", path: "/workspaces/:workspaceId/reminders", module: "reminders" },
  { method: "GET", path: "/workspaces/:workspaceId/reminders/my", module: "reminders" },
  { method: "GET", path: "/workspaces/:workspaceId/reminders/upcoming", module: "reminders" },
  { method: "GET", path: "/workspaces/:workspaceId/reminders/overdue", module: "reminders" },
  { method: "GET", path: "/workspaces/:workspaceId/reminders/capabilities", module: "reminders" },
  { method: "GET", path: "/workspaces/:workspaceId/reminders/:id", module: "reminders" },
  { method: "POST", path: "/workspaces/:workspaceId/reminders", module: "reminders" },
  { method: "PATCH", path: "/workspaces/:workspaceId/reminders/:id", module: "reminders" },
  { method: "DELETE", path: "/workspaces/:workspaceId/reminders/:id", module: "reminders" },
  { method: "POST", path: "/workspaces/:workspaceId/reminders/:id/snooze", module: "reminders" },
  { method: "POST", path: "/workspaces/:workspaceId/reminders/:id/reschedule", module: "reminders" },
  { method: "POST", path: "/workspaces/:workspaceId/reminders/:id/complete", module: "reminders" },
  { method: "POST", path: "/workspaces/:workspaceId/reminders/:id/cancel", module: "reminders" },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/:parentType/:parentId/reminders",
    module: "reminders",
    notes: "List reminders for a Task, Call, or Meeting",
  },
  {
    method: "POST",
    path: "/workspaces/:workspaceId/:parentType/:parentId/reminders",
    module: "reminders",
    notes: "Create an additional custom reminder on a Task, Call, or Meeting",
  },

  // Reports (JWT)
  { method: "GET", path: "/reports", module: "reports", notes: "List reports" },
  { method: "POST", path: "/reports", module: "reports", notes: "Create a report" },
  { method: "GET", path: "/reports/:id", module: "reports" },
  { method: "PATCH", path: "/reports/:id", module: "reports" },
  { method: "DELETE", path: "/reports/:id", module: "reports", notes: "Soft-delete" },
  { method: "POST", path: "/reports/:id/run", module: "reports" },
  { method: "GET", path: "/reports/:id/export", module: "reports", notes: "PDF, Excel, CSV" },
  { method: "POST", path: "/reports/:id/template", module: "reports", notes: "Save as reusable template" },
  { method: "POST", path: "/reports/:id/email", module: "reports", notes: "Email report export" },
  { method: "POST", path: "/reports/:id/share", module: "reports", notes: "Share with team or role" },

  // Calculator history (JWT)
  { method: "GET", path: "/calculations", module: "calculations", notes: "List saved calculator results" },
  { method: "POST", path: "/calculations", module: "calculations", notes: "Save a calculator result" },
  { method: "GET", path: "/calculations/:id", module: "calculations" },
  { method: "DELETE", path: "/calculations/:id", module: "calculations", notes: "Soft-delete" },

  // Smart Link hubs and short URLs (JWT)
  { method: "GET", path: "/smart-hubs", module: "smart-links", notes: "List Smart Link hubs" },
  { method: "POST", path: "/smart-hubs", module: "smart-links", notes: "Create a Smart Link hub" },
  { method: "GET", path: "/smart-hubs/:id", module: "smart-links" },
  { method: "PATCH", path: "/smart-hubs/:id", module: "smart-links" },
  { method: "DELETE", path: "/smart-hubs/:id", module: "smart-links", notes: "Soft-delete" },
  { method: "GET", path: "/smart-short-links", module: "smart-links", notes: "List shortened links" },
  { method: "POST", path: "/smart-short-links", module: "smart-links", notes: "Create a shortened link" },
  { method: "DELETE", path: "/smart-short-links/:id", module: "smart-links", notes: "Soft-delete" },
  { method: "GET", path: "/public/smart-hubs/:slug", module: "public-smart-links", notes: "View a published hub" },
  { method: "GET", path: "/public/smart-short-links/:alias", module: "public-smart-links", notes: "Resolve a short link" },

  // Resources (JWT)
  { method: "GET", path: "/resources", module: "resources", notes: "List resources" },
  { method: "POST", path: "/resources", module: "resources", notes: "Create a resource" },
  { method: "GET", path: "/resources/:id", module: "resources" },
  { method: "PATCH", path: "/resources/:id", module: "resources" },
  { method: "DELETE", path: "/resources/:id", module: "resources", notes: "Soft-delete" },

  // Private object storage (JWT)
  {
    method: "POST",
    path: "/storage/upload",
    module: "storage",
    notes: "Upload a file to private object storage",
  },

  // Signature requests (JWT; workspace-scoped URL preferred when token has workspaceId)
  { method: "GET", path: "/signature-requests", module: "signature-requests", notes: "List workspace signature requests" },
  { method: "POST", path: "/signature-requests", module: "signature-requests", notes: "Create an internal workspace signature request" },
  { method: "GET", path: "/signature-requests/:id", module: "signature-requests" },
  { method: "PATCH", path: "/signature-requests/:id", module: "signature-requests", notes: "Update DRAFT metadata" },
  { method: "DELETE", path: "/signature-requests/:id", module: "signature-requests", notes: "Delete DRAFT or cancel active" },
  { method: "GET", path: "/signature-requests/:id/download", module: "signature-requests", notes: "Private signed-document URL" },
  { method: "POST", path: "/signature-requests/:id/send", module: "signature-requests" },
  { method: "POST", path: "/signature-requests/:id/view", module: "signature-requests" },
  { method: "POST", path: "/signature-requests/:id/sign", module: "signature-requests" },
  { method: "POST", path: "/signature-requests/:id/decline", module: "signature-requests" },
  { method: "GET", path: "/workspaces/:workspaceId/signature-requests", module: "signature-requests" },
  { method: "POST", path: "/workspaces/:workspaceId/signature-requests", module: "signature-requests" },
  { method: "GET", path: "/workspaces/:workspaceId/signature-requests/:id", module: "signature-requests" },
  { method: "PATCH", path: "/workspaces/:workspaceId/signature-requests/:id", module: "signature-requests" },
  { method: "DELETE", path: "/workspaces/:workspaceId/signature-requests/:id", module: "signature-requests" },
  { method: "GET", path: "/workspaces/:workspaceId/signature-requests/:id/download", module: "signature-requests" },
  { method: "POST", path: "/workspaces/:workspaceId/signature-requests/:id/send", module: "signature-requests" },
  { method: "POST", path: "/workspaces/:workspaceId/signature-requests/:id/view", module: "signature-requests" },
  { method: "POST", path: "/workspaces/:workspaceId/signature-requests/:id/sign", module: "signature-requests" },
  { method: "POST", path: "/workspaces/:workspaceId/signature-requests/:id/decline", module: "signature-requests" },

  // Document requests (JWT; workspace-scoped URL preferred when token has workspaceId)
  { method: "GET", path: "/document-requests", module: "document-requests" },
  { method: "GET", path: "/document-requests/:id", module: "document-requests" },
  { method: "POST", path: "/document-requests", module: "document-requests" },
  { method: "PATCH", path: "/document-requests/:id", module: "document-requests", notes: "Edit REQUESTED metadata" },
  { method: "DELETE", path: "/document-requests/:id", module: "document-requests", notes: "Soft-delete" },
  { method: "POST", path: "/document-requests/:id/restore", module: "document-requests" },
  { method: "POST", path: "/document-requests/:id/send", module: "document-requests", notes: "REQUESTED → PENDING" },
  { method: "POST", path: "/document-requests/:id/receive", module: "document-requests", notes: "PENDING → RECEIVED" },
  { method: "POST", path: "/document-requests/:id/approve", module: "document-requests" },
  { method: "POST", path: "/document-requests/:id/reject", module: "document-requests" },
  { method: "POST", path: "/document-requests/:id/expire", module: "document-requests" },
  { method: "GET", path: "/workspaces/:workspaceId/document-requests", module: "document-requests" },
  { method: "GET", path: "/workspaces/:workspaceId/document-requests/:id", module: "document-requests" },
  { method: "POST", path: "/workspaces/:workspaceId/document-requests", module: "document-requests" },
  { method: "PATCH", path: "/workspaces/:workspaceId/document-requests/:id", module: "document-requests" },
  { method: "DELETE", path: "/workspaces/:workspaceId/document-requests/:id", module: "document-requests" },
  { method: "POST", path: "/workspaces/:workspaceId/document-requests/:id/restore", module: "document-requests" },
  { method: "POST", path: "/workspaces/:workspaceId/document-requests/:id/send", module: "document-requests" },
  { method: "POST", path: "/workspaces/:workspaceId/document-requests/:id/receive", module: "document-requests" },
  { method: "POST", path: "/workspaces/:workspaceId/document-requests/:id/approve", module: "document-requests" },
  { method: "POST", path: "/workspaces/:workspaceId/document-requests/:id/reject", module: "document-requests" },
  { method: "POST", path: "/workspaces/:workspaceId/document-requests/:id/expire", module: "document-requests" },

  // Documents library (JWT; workspace-scoped URL preferred when token has workspaceId)
  { method: "GET", path: "/documents", module: "documents", notes: "List readable active documents" },
  { method: "GET", path: "/documents/:id", module: "documents" },
  { method: "GET", path: "/documents/:id/download", module: "documents", notes: "Short-lived download URL" },
  { method: "POST", path: "/documents", module: "documents", notes: "Register private workspace document" },
  { method: "PATCH", path: "/documents/:id", module: "documents", notes: "Update metadata" },
  { method: "DELETE", path: "/documents/:id", module: "documents", notes: "Soft-delete metadata" },
  { method: "POST", path: "/documents/:id/restore", module: "documents" },
  { method: "GET", path: "/workspaces/:workspaceId/documents", module: "documents" },
  { method: "GET", path: "/workspaces/:workspaceId/documents/:id", module: "documents" },
  { method: "GET", path: "/workspaces/:workspaceId/documents/:id/download", module: "documents" },
  { method: "POST", path: "/workspaces/:workspaceId/documents", module: "documents" },
  { method: "PATCH", path: "/workspaces/:workspaceId/documents/:id", module: "documents" },
  { method: "DELETE", path: "/workspaces/:workspaceId/documents/:id", module: "documents" },
  { method: "POST", path: "/workspaces/:workspaceId/documents/:id/restore", module: "documents" },

  // Work Queue (workspace-scoped; current member, read-only)
  {
    method: "GET",
    path: "/workspaces/:workspaceId/work-queue",
    module: "work-queue",
    notes: "Normalized activity queue with related CRM fields; query: page, limit, type, status, priority, assigneeId, from, to (max 10 years)",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/search/records",
    module: "search",
    notes: "Search safe workspace CRM record summaries; query: q",
  },

  // Support
  { method: "GET", path: "/tickets", module: "tickets", notes: "List support tickets" },
  { method: "POST", path: "/tickets", module: "tickets" },
  { method: "GET", path: "/tickets/:id", module: "tickets" },
  { method: "PATCH", path: "/tickets/:id", module: "tickets" },
  { method: "DELETE", path: "/tickets/:id", module: "tickets", notes: "Soft-delete" },
  { method: "GET", path: "/tickets/:id/replies", module: "tickets" },
  { method: "POST", path: "/tickets/:id/replies", module: "tickets" },
  { method: "GET", path: "/tickets/:id/notes", module: "tickets" },
  { method: "POST", path: "/tickets/:id/notes", module: "tickets" },
  { method: "POST", path: "/tickets/:id/merge", module: "tickets" },
  { method: "POST", path: "/tickets/:id/suggest-reply", module: "tickets" },

  // Workflow rules (JWT; global)
  { method: "GET", path: "/workflow-rules", module: "workflow-rules", notes: "List workflow rules" },
  { method: "POST", path: "/workflow-rules", module: "workflow-rules", notes: "Create a workflow rule" },
  { method: "GET", path: "/workflow-rules/:id", module: "workflow-rules" },
  { method: "PATCH", path: "/workflow-rules/:id", module: "workflow-rules" },
  {
    method: "DELETE",
    path: "/workflow-rules/:id",
    module: "workflow-rules",
    notes: "Soft-delete a workflow rule",
  },
  {
    method: "POST",
    path: "/workflow-rules/suggest",
    module: "workflow-rules",
    notes: "Generate a suggested rule from a natural-language description",
  },

  // Rules (§28)
  { method: "GET", path: "/rules/audit", module: "rules" },
  { method: "GET", path: "/rules/recycle-bin", module: "rules" },
  { method: "POST", path: "/rules/recycle-bin/:id/restore", module: "rules" },
  { method: "DELETE", path: "/rules/recycle-bin/:id", module: "rules", notes: "Permanent purge" },
  {
    method: "GET",
    path: "/recycle-bin",
    module: "recycle-bin",
    notes: "List workspace soft-deleted records; query: entityType",
  },
  {
    method: "POST",
    path: "/recycle-bin/:entityType/:id/restore",
    module: "recycle-bin",
    notes: "Restore a soft-deleted record",
  },
  {
    method: "DELETE",
    path: "/recycle-bin/:entityType/:id",
    module: "recycle-bin",
    notes: "Permanently delete a soft-deleted record",
  },
  { method: "GET", path: "/rules/permissions/me", module: "rules" },
  { method: "GET", path: "/audit-logs", module: "audit-logs", notes: "Paginated audit trail; query: page, limit, search, action, entityType" },

  // Custom fields (JWT; workspace via token claim)
  { method: "GET", path: "/custom-fields", module: "custom-fields", notes: "List definitions" },
  { method: "GET", path: "/custom-fields/:id", module: "custom-fields" },
  { method: "POST", path: "/custom-fields", module: "custom-fields" },
  { method: "PATCH", path: "/custom-fields/:id", module: "custom-fields" },
  { method: "DELETE", path: "/custom-fields/:id", module: "custom-fields", notes: "Soft-delete" },
  { method: "POST", path: "/custom-fields/:id/restore", module: "custom-fields" },
  { method: "GET", path: "/custom-fields/values/:entityId", module: "custom-fields" },
  { method: "POST", path: "/custom-fields/:id/values", module: "custom-fields" },
  {
    method: "DELETE",
    path: "/custom-fields/:id/values/:entityId",
    module: "custom-fields",
  },
  { method: "GET", path: "/custom-fields/definitions/export", module: "custom-fields" },
  { method: "GET", path: "/custom-fields/:id/usage", module: "custom-fields" },
  { method: "GET", path: "/custom-fields/:id/value-search", module: "custom-fields" },
  { method: "POST", path: "/custom-fields/preview", module: "custom-fields" },
  { method: "POST", path: "/custom-fields/reorder", module: "custom-fields" },
  { method: "POST", path: "/custom-fields/import", module: "custom-fields" },
  { method: "POST", path: "/custom-fields/values/bulk", module: "custom-fields" },

  // Workspace settings (JWT; workspace via token claim)
  { method: "GET", path: "/settings", module: "settings", notes: "Get workspace settings" },
  { method: "PATCH", path: "/settings", module: "settings", notes: "Update workspace settings" },
  { method: "GET", path: "/settings/security", module: "settings", notes: "Safe security subset" },
  { method: "GET", path: "/settings/capabilities", module: "settings", notes: "Enabled modules" },
  { method: "POST", path: "/settings/smtp-test", module: "settings", notes: "Queue SMTP connectivity test" },
  { method: "GET", path: "/settings/smtp-test/:jobId", module: "settings", notes: "SMTP test job status" },

  // Notification preferences (JWT; workspace-scoped URL preferred when token has workspaceId)
  {
    method: "GET",
    path: "/notification-preferences",
    module: "notification-preferences",
    notes: "Current user notification preferences",
  },
  {
    method: "PATCH",
    path: "/notification-preferences",
    module: "notification-preferences",
    notes: "Upsert preferences and FCM device token",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/notification-preferences",
    module: "notification-preferences",
  },
  {
    method: "PATCH",
    path: "/workspaces/:workspaceId/notification-preferences",
    module: "notification-preferences",
  },

  // Per-user table layout (JWT; workspace-scoped)
  {
    method: "GET",
    path: "/workspaces/:workspaceId/preferences/tables/:tableKey",
    module: "table-preferences",
    notes: "Get my validated table preference",
  },
  {
    method: "PUT",
    path: "/workspaces/:workspaceId/preferences/tables/:tableKey",
    module: "table-preferences",
    notes: "Replace my validated table preference",
  },
  {
    method: "DELETE",
    path: "/workspaces/:workspaceId/preferences/tables/:tableKey",
    module: "table-preferences",
    notes: "Reset my table preference to safe defaults",
  },

  // CRM notifications inbox (JWT; workspace-scoped URL preferred when token has workspaceId)
  { method: "GET", path: "/notifications", module: "notifications", notes: "List personal notifications" },
  { method: "GET", path: "/notifications/unread-count", module: "notifications" },
  { method: "GET", path: "/notifications/:id", module: "notifications" },
  { method: "POST", path: "/notifications/read-all", module: "notifications", notes: "Mark all read" },
  { method: "POST", path: "/notifications/:id/read", module: "notifications" },
  { method: "POST", path: "/notifications/:id/unread", module: "notifications" },
  { method: "PATCH", path: "/notifications/read-all", module: "notifications", notes: "Mark all read (compatibility)" },
  { method: "PATCH", path: "/notifications/:id/read", module: "notifications" },
  { method: "PATCH", path: "/notifications/:id/dismiss", module: "notifications" },
  { method: "DELETE", path: "/notifications/clear-read", module: "notifications", notes: "Archive all read" },
  { method: "DELETE", path: "/notifications/:id", module: "notifications", notes: "Archive one" },
  { method: "GET", path: "/workspaces/:workspaceId/notifications", module: "notifications" },
  { method: "GET", path: "/workspaces/:workspaceId/notifications/unread-count", module: "notifications" },
  { method: "GET", path: "/workspaces/:workspaceId/notifications/:id", module: "notifications" },
  { method: "POST", path: "/workspaces/:workspaceId/notifications/read-all", module: "notifications" },
  { method: "POST", path: "/workspaces/:workspaceId/notifications/:id/read", module: "notifications" },
  { method: "POST", path: "/workspaces/:workspaceId/notifications/:id/unread", module: "notifications" },
  { method: "PATCH", path: "/workspaces/:workspaceId/notifications/read-all", module: "notifications" },
  { method: "PATCH", path: "/workspaces/:workspaceId/notifications/:id/read", module: "notifications" },
  { method: "PATCH", path: "/workspaces/:workspaceId/notifications/:id/dismiss", module: "notifications" },
  { method: "DELETE", path: "/workspaces/:workspaceId/notifications/clear-read", module: "notifications" },
  { method: "DELETE", path: "/workspaces/:workspaceId/notifications/:id", module: "notifications" },

  // Campaigns (email/SMS; JWT required)
  { method: "GET", path: "/campaigns", module: "campaigns", notes: "List email/SMS campaigns" },
  { method: "GET", path: "/campaigns/:id", module: "campaigns" },
  { method: "POST", path: "/campaigns", module: "campaigns", notes: "Create email or SMS campaign" },
  { method: "PATCH", path: "/campaigns/:id", module: "campaigns" },
  { method: "DELETE", path: "/campaigns/:id", module: "campaigns", notes: "Soft-delete" },
  { method: "POST", path: "/campaigns/:id/launch", module: "campaigns" },

  // Team Chat (workspace-scoped)
  {
    method: "GET",
    path: "/workspaces/:workspaceId/chat/conversations",
    module: "team-chat",
    notes: "List participant conversations",
  },
  {
    method: "POST",
    path: "/workspaces/:workspaceId/chat/conversations",
    module: "team-chat",
    notes: "Create or reuse conversation",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/chat/conversations/:conversationId",
    module: "team-chat",
  },
  {
    method: "PATCH",
    path: "/workspaces/:workspaceId/chat/conversations/:conversationId",
    module: "team-chat",
    notes: "Update group as owner",
  },
  {
    method: "DELETE",
    path: "/workspaces/:workspaceId/chat/conversations/:conversationId",
    module: "team-chat",
    notes: "Soft-delete as owner",
  },
  {
    method: "POST",
    path: "/workspaces/:workspaceId/chat/conversations/:conversationId/members",
    module: "team-chat",
  },
  {
    method: "DELETE",
    path: "/workspaces/:workspaceId/chat/conversations/:conversationId/members/:userId",
    module: "team-chat",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/chat/conversations/:conversationId/messages",
    module: "team-chat",
    notes: "Cursor-paginated messages",
  },
  {
    method: "POST",
    path: "/workspaces/:workspaceId/chat/conversations/:conversationId/messages",
    module: "team-chat",
  },
  {
    method: "POST",
    path: "/workspaces/:workspaceId/chat/conversations/:conversationId/read",
    module: "team-chat",
  },
  {
    method: "PATCH",
    path: "/workspaces/:workspaceId/chat/messages/:messageId",
    module: "team-chat",
    notes: "Edit within policy window",
  },
  {
    method: "DELETE",
    path: "/workspaces/:workspaceId/chat/messages/:messageId",
    module: "team-chat",
  },
  {
    method: "POST",
    path: "/workspaces/:workspaceId/chat/messages/:messageId/read",
    module: "team-chat",
  },
  {
    method: "POST",
    path: "/workspaces/:workspaceId/chat/messages/:messageId/reactions",
    module: "team-chat",
  },
  {
    method: "DELETE",
    path: "/workspaces/:workspaceId/chat/messages/:messageId/reactions/:reaction",
    module: "team-chat",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/chat/unread-count",
    module: "team-chat",
  },

  // Client portals
  { method: "GET", path: "/client-portals", module: "client-portals" },
  { method: "GET", path: "/client-portals/:id", module: "client-portals" },
  { method: "POST", path: "/client-portals", module: "client-portals" },
  { method: "PATCH", path: "/client-portals/:id", module: "client-portals" },
  { method: "DELETE", path: "/client-portals/:id", module: "client-portals", notes: "Soft-delete" },
  {
    method: "POST",
    path: "/client-portals/:id/reset-password",
    module: "client-portals",
    notes: "Email password reset to primary contact",
  },

  // Activity Timeline (workspace-scoped; requires JWT workspaceId)
  {
    method: "GET",
    path: "/workspaces/:workspaceId/activity-timeline",
    module: "activity-timeline",
    notes: "Workspace feed; query: page, limit, type, from, to",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/:relatedType/:relatedId/activity-timeline",
    module: "activity-timeline",
    notes: "Parent feed; relatedType=LEAD|CONTACT|COMPANY|DEAL|…",
  },

  // Analytics (workspace JWT required; query widget= enum)
  {
    method: "GET",
    path: "/analytics",
    module: "analytics",
    notes:
      "Widget KPI; query: widget, startDate, endDate, comparePeriod=previous_period|previous_year",
  },

  // Platform admin
  {
    method: "GET",
    path: "/admin/workspaces",
    module: "admin",
    notes: "ADMIN only; paginated workspace list",
  },
  {
    method: "DELETE",
    path: "/admin/user/:id",
    module: "admin",
    notes: "ADMIN only; delete a user",
  },

  // Calendar (GET-only; JWT required; prefer workspace-scoped so claim matches URL)
  {
    method: "GET",
    path: "/calendar",
    module: "calendar",
    notes: "Normalized events in a bounded from/to range",
  },
  {
    method: "GET",
    path: "/calendar/events",
    module: "calendar",
    notes: "Alias of /calendar (bounded range)",
  },
  {
    method: "GET",
    path: "/calendar/day",
    module: "calendar",
    notes: "Timezone-aware day view; query: date, timezone",
  },
  {
    method: "GET",
    path: "/calendar/week",
    module: "calendar",
    notes: "Monday–Sunday week; query: date, timezone",
  },
  {
    method: "GET",
    path: "/calendar/month",
    module: "calendar",
    notes: "Timezone-aware month; query: year, month, timezone",
  },
  {
    method: "GET",
    path: "/calendar/upcoming",
    module: "calendar",
    notes: "Next 30 calendar days",
  },
  {
    method: "GET",
    path: "/calendar/conflicts",
    module: "calendar",
    notes: "Overlapping accessible non-cancelled events",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/calendar",
    module: "calendar",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/calendar/events",
    module: "calendar",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/calendar/day",
    module: "calendar",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/calendar/week",
    module: "calendar",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/calendar/month",
    module: "calendar",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/calendar/upcoming",
    module: "calendar",
  },
  {
    method: "GET",
    path: "/workspaces/:workspaceId/calendar/conflicts",
    module: "calendar",
  },
] as const;

/** Screenshot APIs from live Swagger (Activity Timeline + admin + analytics). */
export const SCREENSHOT_ENDPOINTS = [
  {
    key: "workspaceTimeline",
    method: "GET",
    path: "/v1/workspaces/:workspaceId/activity-timeline",
    module: "activity-timeline",
  },
  {
    key: "parentTimeline",
    method: "GET",
    path: "/v1/workspaces/:workspaceId/:relatedType/:relatedId/activity-timeline",
    module: "activity-timeline",
  },
  {
    key: "adminWorkspaces",
    method: "GET",
    path: "/v1/admin/workspaces",
    module: "admin",
  },
  {
    key: "adminDeleteUser",
    method: "DELETE",
    path: "/v1/admin/user/:id",
    module: "admin",
  },
  {
    key: "analyticsWidget",
    method: "GET",
    path: "/v1/analytics",
    module: "analytics",
  },
] as const;

export type EndpointEntry = (typeof ENDPOINT_CATALOG)[number];
