export interface SubItem {
  title: string;
  slug: string;
}

export interface Category {
  title: string;
  slug: string;
  icon: string;
  items: SubItem[];
}

export const SETTINGS_CATEGORIES: Category[] = [
  {
    title: "Organization",
    slug: "organization",
    icon: "Building2",
    items: [
      { title: "Company Profile", slug: "company-profile" },
      { title: "Branding", slug: "branding" },
      { title: "Business Information", slug: "business-information" },
      { title: "Business Hours", slug: "business-hours" },
      { title: "Holidays", slug: "holidays" },
      { title: "Time Zone", slug: "time-zone" },
      { title: "Language", slug: "language" },
      { title: "Currency", slug: "currency" },
      { title: "Regional Settings", slug: "regional-settings" },
      { title: "Date Format", slug: "date-format" },
      { title: "Time Format", slug: "time-format" },
      { title: "Number Format", slug: "number-format" },
      { title: "Multi-Currency", slug: "multi-currency" },
      { title: "Multi-Language", slug: "multi-language" },
      { title: "Themes", slug: "themes" },
      { title: "Dark Mode", slug: "dark-mode" },
      { title: "Accent Colors", slug: "accent-colors" },
      { title: "Sidebar Layout", slug: "sidebar-layout" },
      { title: "White Label", slug: "white-label" },
      { title: "Email Branding", slug: "email-branding" },
      { title: "Login Page Branding", slug: "login-page-branding" },
      { title: "Favicon", slug: "favicon" },
    ],
  },
  {
    title: "Users & Access",
    slug: "users-and-access",
    icon: "Users",
    items: [
      { title: "Users", slug: "users" },
      { title: "Teams", slug: "teams" },
      { title: "Departments", slug: "departments" },
      { title: "Roles", slug: "roles" },
      { title: "Permissions", slug: "permissions" },
      { title: "Reporting Hierarchy", slug: "reporting-hierarchy" },
      { title: "User Groups", slug: "user-groups" },
      { title: "Login Sessions", slug: "login-sessions" },
      { title: "User Activity", slug: "user-activity" },
    ],
  },
  {
    title: "CRM Configuration",
    slug: "crm-configuration",
    icon: "Briefcase",
    items: [
      { title: "Pipelines", slug: "pipelines" },
      { title: "Lead Statuses", slug: "lead-statuses" },
      { title: "Deal Stages", slug: "deal-stages" },
      { title: "Lead Sources", slug: "lead-sources" },
      { title: "Lost Reasons", slug: "lost-reasons" },
      { title: "Tags", slug: "tags" },
      { title: "Labels", slug: "labels" },
      { title: "Custom Fields", slug: "custom-fields" },
      { title: "Custom Objects", slug: "custom-objects" },
      { title: "Record Layouts", slug: "record-layouts" },
      { title: "Record Types", slug: "record-types" },
      { title: "Number Sequences", slug: "number-sequences" },
      { title: "Duplicate Rules", slug: "duplicate-rules" },
      { title: "Field Validation Rules", slug: "field-validation-rules" },
    ],
  },
  {
    title: "Workflow & Automation",
    slug: "workflow-and-automation",
    icon: "GitBranch",
    items: [
      { title: "Workflow Builder", slug: "workflow-builder" },
      { title: "Workflow Templates", slug: "workflow-templates" },
      { title: "Approval Workflows", slug: "approval-workflows" },
      { title: "Assignment Rules", slug: "assignment-rules" },
      { title: "Round Robin", slug: "round-robin" },
      { title: "SLA Rules", slug: "sla-rules" },
      { title: "Escalation Rules", slug: "escalation-rules" },
      { title: "Scheduled Jobs", slug: "scheduled-jobs" },
      { title: "Automation Logs", slug: "automation-logs" },
    ],
  },
  {
    title: "Communication",
    slug: "communication",
    icon: "MessageSquare",
    items: [
      { title: "Email Accounts", slug: "email-accounts" },
      { title: "SMTP", slug: "smtp" },
      { title: "IMAP", slug: "imap" },
      { title: "Email Signatures", slug: "email-signatures" },
      { title: "Sender Profiles", slug: "sender-profiles" },
      { title: "Sending Domains", slug: "sending-domains" },
      { title: "Phone Numbers", slug: "phone-numbers" },
      { title: "SMS Providers", slug: "sms-providers" },
      { title: "WhatsApp", slug: "whatsapp" },
      { title: "Call Settings", slug: "call-settings" },
      { title: "Calendar Settings", slug: "calendar-settings" },
    ],
  },
  {
    title: "Templates",
    slug: "templates",
    icon: "FileText",
    items: [
      { title: "Email Templates", slug: "email-templates" },
      { title: "SMS Templates", slug: "sms-templates" },
      { title: "WhatsApp Templates", slug: "whatsapp-templates" },
      { title: "Message Templates", slug: "message-templates" },
      { title: "Document Templates", slug: "document-templates" },
      { title: "Proposal Templates", slug: "proposal-templates" },
      { title: "Quote Templates", slug: "quote-templates" },
      { title: "Invoice Templates", slug: "invoice-templates" },
      { title: "Task Templates", slug: "task-templates" },
      { title: "Workflow Templates", slug: "workflow-templates" },
    ],
  },
  {
    title: "Forms & Client Experience",
    slug: "forms-and-client-experience",
    icon: "Layout",
    items: [
      { title: "Forms", slug: "forms" },
      { title: "Form Themes", slug: "form-themes" },
      { title: "Linktree", slug: "linktree" },
      { title: "Client Portal", slug: "client-portal" },
      { title: "Public Pages", slug: "public-pages" },
      { title: "Custom Domains", slug: "custom-domains" },
    ],
  },
  {
    title: "Finance",
    slug: "finance",
    icon: "DollarSign",
    items: [
      { title: "Taxes", slug: "taxes" },
      { title: "Invoice Settings", slug: "invoice-settings" },
      { title: "Quote Settings", slug: "quote-settings" },
      { title: "Payment Gateways", slug: "payment-gateways" },
      { title: "Commission Rules", slug: "commission-rules" },
      { title: "Product Categories", slug: "product-categories" },
      { title: "Pricing Rules", slug: "pricing-rules" },
    ],
  },
  {
    title: "AI",
    slug: "ai",
    icon: "Cpu",
    items: [
      { title: "AI Providers", slug: "ai-providers" },
      { title: "AI Models", slug: "ai-models" },
      { title: "AI Prompts", slug: "ai-prompts" },
      { title: "AI Templates", slug: "ai-templates" },
      { title: "AI Permissions", slug: "ai-permissions" },
      { title: "AI Usage", slug: "ai-usage" },
      { title: "AI Credits", slug: "ai-credits" },
      { title: "AI Logs", slug: "ai-logs" },
    ],
  },
  {
    title: "Integrations",
    slug: "integrations",
    icon: "Puzzle",
    items: [
      { title: "Google", slug: "google" },
      { title: "Microsoft 365", slug: "microsoft-365" },
      { title: "Outlook", slug: "outlook" },
      { title: "Gmail", slug: "gmail" },
      { title: "Google Calendar", slug: "google-calendar" },
      { title: "Outlook Calendar", slug: "outlook-calendar" },
      { title: "Zoom", slug: "zoom" },
      { title: "Microsoft Teams", slug: "microsoft-teams" },
      { title: "Twilio", slug: "twilio" },
      { title: "Stripe", slug: "stripe" },
      { title: "Xero", slug: "xero" },
      { title: "MYOB", slug: "myob" },
      { title: "QuickBooks", slug: "quickbooks" },
      { title: "Google Drive", slug: "google-drive" },
      { title: "OneDrive", slug: "onedrive" },
      { title: "Dropbox", slug: "dropbox" },
      { title: "Zapier", slug: "zapier" },
      { title: "Make", slug: "make" },
      { title: "Webhooks", slug: "webhooks" },
      { title: "API Keys", slug: "api-keys" },
      { title: "OAuth Apps", slug: "oauth-apps" },
    ],
  },
  {
    title: "Security",
    slug: "security",
    icon: "Shield",
    items: [
      { title: "Password Policy", slug: "password-policy" },
      { title: "Two-Factor Authentication", slug: "two-factor-authentication" },
      { title: "Single Sign-On (SSO)", slug: "single-sign-on" },
      { title: "IP Restrictions", slug: "ip-restrictions" },
      { title: "Device Management", slug: "device-management" },
      { title: "Session Timeout", slug: "session-timeout" },
      { title: "Login History", slug: "login-history" },
      { title: "Audit Logs", slug: "audit-logs" },
      { title: "Encryption", slug: "encryption" },
      { title: "Data Retention", slug: "data-retention" },
      { title: "GDPR Settings", slug: "gdpr-settings" },
      { title: "Privacy & Consent", slug: "privacy-and-consent" },
      { title: "Cookie Management", slug: "cookie-management" },
      { title: "Data Residency", slug: "data-residency" },
      { title: "Consent Management", slug: "consent-management" },
    ],
  },
  {
    title: "Notifications",
    slug: "notifications",
    icon: "Bell",
    items: [
      { title: "Email Notifications", slug: "email-notifications" },
      { title: "SMS Notifications", slug: "sms-notifications" },
      { title: "Push Notifications", slug: "push-notifications" },
      { title: "In-App Notifications", slug: "in-app-notifications" },
      { title: "Notification Rules", slug: "notification-rules" },
      { title: "Mentions", slug: "mentions" },
      { title: "Digest Settings", slug: "digest-settings" },
      {
        title: "Push Notification Settings",
        slug: "push-notification-settings",
      },
      { title: "Mobile App Settings", slug: "mobile-app-settings" },
    ],
  },
  {
    title: "Reports & Analytics",
    slug: "reports-and-analytics",
    icon: "BarChart3",
    items: [
      { title: "Dashboard Builder", slug: "dashboard-builder" },
      { title: "Report Templates", slug: "report-templates" },
      { title: "Scheduled Reports", slug: "scheduled-reports" },
      { title: "KPI Targets", slug: "kpi-targets" },
      { title: "Forecast Settings", slug: "forecast-settings" },
      { title: "Dashboard Layout", slug: "dashboard-layout" },
    ],
  },
  {
    title: "Data Management",
    slug: "data-management",
    icon: "Database",
    items: [
      { title: "Import Data", slug: "import-data" },
      { title: "Export Data", slug: "export-data" },
      { title: "Backup & Restore", slug: "backup-and-restore" },
      { title: "Archive", slug: "archive" },
      { title: "Recycle Bin", slug: "recycle-bin" },
      { title: "Merge Records", slug: "merge-records" },
      { title: "Storage Usage", slug: "storage-usage" },
      { title: "Scheduled Backups", slug: "scheduled-backups" },
      { title: "Restore Points", slug: "restore-points" },
    ],
  },
  {
    title: "Marketplace",
    slug: "marketplace",
    icon: "Store",
    items: [
      { title: "Installed Apps", slug: "installed-apps" },
      { title: "Marketplace", slug: "marketplace" },
      { title: "Extensions", slug: "extensions" },
      { title: "Themes", slug: "themes" },
    ],
  },
  {
    title: "Subscription & Billing",
    slug: "subscription-and-billing",
    icon: "CreditCard",
    items: [
      { title: "Subscription Plan", slug: "subscription-plan" },
      { title: "Users", slug: "users" },
      { title: "Storage", slug: "storage" },
      { title: "Usage", slug: "usage" },
      { title: "Billing", slug: "billing" },
      { title: "Payment Methods", slug: "payment-methods" },
      { title: "Invoices", slug: "invoices" },
      { title: "Add-ons", slug: "add-ons" },
    ],
  },
  {
    title: "Developer",
    slug: "developer",
    icon: "Code",
    items: [
      { title: "API Keys", slug: "api-keys" },
      { title: "OAuth Apps", slug: "oauth-apps" },
      { title: "Webhooks", slug: "webhooks" },
      { title: "SDK", slug: "sdk" },
      { title: "Event Logs", slug: "event-logs" },
      { title: "API Usage", slug: "api-usage" },
      { title: "Custom Scripts", slug: "custom-scripts" },
    ],
  },
  {
    title: "System",
    slug: "system",
    icon: "Settings",
    items: [
      { title: "Feature Flags", slug: "feature-flags" },
      { title: "Maintenance Mode", slug: "maintenance-mode" },
      { title: "Queue Monitor", slug: "queue-monitor" },
      { title: "Email Queue", slug: "email-queue" },
      { title: "SMS Queue", slug: "sms-queue" },
      { title: "Workflow Queue", slug: "workflow-queue" },
      { title: "Background Jobs", slug: "background-jobs" },
      { title: "System Health", slug: "system-health" },
      { title: "Error Logs", slug: "error-logs" },
      { title: "Version", slug: "version" },
      { title: "Enable/Disable Modules", slug: "enable-disable-modules" },
      { title: "Beta Features", slug: "beta-features" },
      { title: "Experimental Features", slug: "experimental-features" },
      { title: "Global Search Settings", slug: "global-search-settings" },
      { title: "Search Index", slug: "search-index" },
    ],
  },
  {
    title: "Help & Support",
    slug: "help-and-support",
    icon: "HelpCircle",
    items: [
      { title: "Knowledge Base", slug: "knowledge-base" },
      { title: "Product Updates", slug: "product-updates" },
      { title: "Training", slug: "training" },
      { title: "Support Tickets", slug: "support-tickets" },
      { title: "Contact Support", slug: "contact-support" },
      { title: "Release Notes", slug: "release-notes" },
    ],
  },
];
