/** Canonical Lead module routes from multi-crm-backend Swagger. */

export const CRM_LEAD_ENDPOINTS = [
  { key: "create", method: "POST", path: "/v1/leads", client: "createCrmLead" },
  { key: "bulk", method: "POST", path: "/v1/leads/bulk", client: "bulkCrmLeads" },
  { key: "import", method: "POST", path: "/v1/leads/import", client: "importCrmLeads" },
  { key: "kanban", method: "GET", path: "/v1/leads/kanban", client: "fetchLeadKanban" },
  { key: "list", method: "GET", path: "/v1/leads", client: "fetchLeadList" },
  { key: "get", method: "GET", path: "/v1/leads/{id}", client: "fetchLeadById" },
  { key: "update", method: "PATCH", path: "/v1/leads/{id}", client: "updateCrmLead" },
  {
    key: "assignOwner",
    method: "PATCH",
    path: "/v1/leads/{id}/owner",
    client: "assignCrmLeadOwner",
  },
  {
    key: "unassignOwner",
    method: "DELETE",
    path: "/v1/leads/{id}/owner",
    client: "unassignCrmLeadOwner",
  },
  {
    key: "linkCompany",
    method: "PATCH",
    path: "/v1/leads/{id}/company",
    client: "linkCrmLeadCompany",
  },
  {
    key: "unlinkCompany",
    method: "DELETE",
    path: "/v1/leads/{id}/company",
    client: "unlinkCrmLeadCompany",
  },
  {
    key: "changeStatus",
    method: "PATCH",
    path: "/v1/leads/{id}/status",
    client: "changeCrmLeadStatus",
  },
  {
    key: "changeLifecycle",
    method: "PATCH",
    path: "/v1/leads/{id}/lifecycle-stage",
    client: "changeCrmLeadLifecycleStage",
  },
  {
    key: "changeRating",
    method: "PATCH",
    path: "/v1/leads/{id}/rating",
    client: "changeCrmLeadRating",
  },
  {
    key: "changeScore",
    method: "PATCH",
    path: "/v1/leads/{id}/score",
    client: "changeCrmLeadScore",
  },
  {
    key: "convert",
    method: "POST",
    path: "/v1/leads/{id}/convert",
    client: "convertCrmLead",
  },
  {
    key: "softDelete",
    method: "DELETE",
    path: "/v1/leads/{id}",
    client: "softDeleteCrmLead",
  },
  {
    key: "importAds",
    method: "POST",
    path: "/v1/leads/import/ads",
    client: "importCrmLeadsFromAds",
  },
  {
    key: "importSheets",
    method: "POST",
    path: "/v1/leads/import/sheets",
    client: "importCrmLeadsFromSheets",
  },
  {
    key: "conversations",
    method: "GET",
    path: "/v1/leads/{id}/conversations",
    client: "fetchLeadConversations",
  },
  {
    key: "postConversation",
    method: "POST",
    path: "/v1/leads/{id}/conversations",
    client: "postLeadConversation",
  },
  {
    key: "creditReport",
    method: "GET",
    path: "/v1/leads/{id}/credit-report",
    client: "fetchLeadCreditReport",
  },
  {
    key: "refreshCreditReport",
    method: "POST",
    path: "/v1/leads/{id}/credit-report/refresh",
    client: "refreshLeadCreditReport",
  },
  {
    key: "changePipelineStage",
    method: "PATCH",
    path: "/v1/leads/{id}/pipeline-stage",
    client: "changeCrmLeadPipelineStage",
  },
  {
    key: "replaceTags",
    method: "PUT",
    path: "/v1/leads/{id}/tags",
    client: "replaceCrmLeadTags",
  },
  {
    key: "replaceFollowers",
    method: "PUT",
    path: "/v1/leads/{id}/followers",
    client: "replaceCrmLeadFollowers",
  },
  {
    key: "addFollower",
    method: "POST",
    path: "/v1/leads/{id}/followers",
    client: "addCrmLeadFollower",
  },
  {
    key: "addFollowerById",
    method: "POST",
    path: "/v1/leads/{id}/followers/{userId}",
    client: "addCrmLeadFollowerById",
  },
  {
    key: "removeFollower",
    method: "DELETE",
    path: "/v1/leads/{id}/followers/{userId}",
    client: "removeCrmLeadFollower",
  },
  {
    key: "getMortgage",
    method: "GET",
    path: "/v1/leads/{id}/mortgage",
    client: "fetchLeadMortgage",
  },
  {
    key: "putMortgage",
    method: "PUT",
    path: "/v1/leads/{id}/mortgage",
    client: "putLeadMortgage",
  },
] as const;

export type CrmLeadEndpoint = (typeof CRM_LEAD_ENDPOINTS)[number];
