import {
  AlarmClock,
  Bell,
  BellOff,
  BellPlus,
  Building2,
  CalendarCheck,
  CalendarClock,
  CalendarOff,
  CalendarPlus,
  CalendarX,
  CheckCircle,
  Clock,
  ClockAlert,
  FileCheck,
  FileCheck2,
  FileUp,
  GitBranch,
  Hand,
  HandCoins,
  Handshake,
  Hourglass,
  Inbox,
  Link as LinkIcon,
  ListPlus,
  Mail,
  MailQuestion,
  MailWarning,
  MessageSquare,
  MessageSquareX,
  Pencil,
  Phone,
  PhoneCall,
  PhoneOff,
  RefreshCw,
  Signature,
  StickyNote,
  Tag,
  Trophy,
  UserCheck,
  UserCog,
  UserPlus,
  Webhook,
  Workflow,
  XCircle,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  "user-plus": UserPlus,
  pencil: Pencil,
  "refresh-cw": RefreshCw,
  "user-cog": UserCog,
  "building-2": Building2,
  handshake: Handshake,
  "git-branch": GitBranch,
  trophy: Trophy,
  "x-circle": XCircle,
  "list-plus": ListPlus,
  "check-circle": CheckCircle,
  "alarm-clock": AlarmClock,
  phone: Phone,
  "phone-call": PhoneCall,
  "phone-off": PhoneOff,
  "message-square": MessageSquare,
  "mail-question": MailQuestion,
  "message-square-x": MessageSquareX,
  mail: Mail,
  "mail-warning": MailWarning,
  "calendar-plus": CalendarPlus,
  "calendar-clock": CalendarClock,
  "calendar-x": CalendarX,
  "calendar-check": CalendarCheck,
  "calendar-off": CalendarOff,
  "file-up": FileUp,
  "file-check": FileCheck,
  "file-check-2": FileCheck2,
  signature: Signature,
  calendar: CalendarClock,
  hourglass: Hourglass,
  clock: Clock,
  "clock-alert": ClockAlert,
  hand: Hand,
  "user-check": UserCheck,
  tag: Tag,
  link: LinkIcon,
  inbox: Inbox,
  bell: Bell,
  "bell-plus": BellPlus,
  "bell-off": BellOff,
  "sticky-note": StickyNote,
  workflow: Workflow,
  webhook: Webhook,
  "money-check": HandCoins,
};

export function StepIcon({ icon, className }: { icon: string; className?: string }) {
  const Icon = ICONS[icon] ?? Workflow;
  return <Icon className={className} />;
}
