/** Canonical FinConnex route catalogs for full-app E2E. */

export const PUBLIC_ROUTES = [
  "/login",
  "/signup",
  "/forgot-password",
  "/verify-email",
  "/reset-password",
  "/f/home-loan-lead",
  "/f/doc-intake",
  "/l/john-smith",
  "/l/sydney",
  "/book/john-discovery",
  "/book/site-visit-syd",
  "/sign/sig-anderson-1",
  "/p/greystone/login",
  "/p/harbour/login",
  "/j/jny-greystone-refinance",
  "/j/jny-harbour-packaging",
] as const;

export const AUTH_GUARDED_ROUTES = [
  "/",
  "/finance",
  "/sales/leads",
  "/notifications",
  "/settings",
] as const;

export const CRM_LIST_ROUTES = [
  "/",
  "/work-queue",
  "/sales/leads",
  "/sales/contacts",
  "/sales/companies",
  "/sales/deals",
  "/sales/forecasting",
  "/activities/tasks",
  "/activities/calls",
  "/activities/messages",
  "/activities/emails",
  "/activities/meetings",
  "/activities/notes",
  "/activities/reminders",
  "/activities/calendar",
  "/activities/team-chat",
  "/booking",
  "/documents/library",
  "/documents/requests",
  "/signature",
  "/marketing/email",
  "/marketing/sms",
  "/marketing/whatsapp",
  "/marketing/forms",
  "/marketing/linktree",
  "/marketing/inbox",
  "/finance",
  "/finance/estimates",
  "/finance/quotations",
  "/finance/invoices",
  "/finance/credit-notes",
  "/finance/payments",
  "/finance/products",
  "/support",
  "/portals",
  "/reports",
  "/analytics",
  "/resources",
  "/calculator",
  "/notifications",
  "/journeys",
  "/time-tracking",
  "/rules",
  "/users",
  "/settings",
  "/settings/organization",
  "/settings/organization/company-profile",
  "/settings/my-preferences",
] as const;

export const CRM_CREATE_ROUTES = [
  "/sales/leads/create",
  "/sales/contacts/create",
  "/sales/companies/create",
  "/sales/deals/create",
  "/activities/tasks/create",
  "/activities/calls/create",
  "/activities/messages/create",
  "/activities/emails/create",
  "/activities/meetings/create",
  "/activities/notes/create",
  "/activities/reminders/create",
  "/booking/create",
  "/documents/requests/create",
  "/signature/create",
  "/marketing/email/create",
  "/marketing/sms/create",
  "/marketing/whatsapp/create",
  "/marketing/forms/create",
  "/marketing/linktree/create",
  "/finance/estimates/create",
  "/finance/quotations/create",
  "/finance/invoices/create",
  "/finance/credit-notes/create",
  "/finance/payments/create",
  "/finance/products/create",
  "/support/create",
  "/portals/create",
  "/reports/create",
  "/resources/create",
  "/journeys/create",
  "/time-tracking/create",
] as const;

export const SALES_ROUTES = [
  "/sales/leads",
  "/sales/contacts",
  "/sales/companies",
  "/sales/deals",
  "/sales/forecasting",
] as const;

export const ACTIVITIES_ROUTES = [
  "/activities/tasks",
  "/activities/calls",
  "/activities/messages",
  "/activities/emails",
  "/activities/meetings",
  "/activities/notes",
  "/activities/reminders",
  "/activities/calendar",
  "/activities/team-chat",
] as const;

export const FINANCE_ROUTES = [
  "/finance",
  "/finance/estimates",
  "/finance/quotations",
  "/finance/invoices",
  "/finance/credit-notes",
  "/finance/payments",
  "/finance/products",
] as const;

export const MARKETING_ROUTES = [
  "/marketing/email",
  "/marketing/sms",
  "/marketing/whatsapp",
  "/marketing/forms",
  "/marketing/linktree",
  "/marketing/inbox",
] as const;

export const DOCUMENTS_ROUTES = [
  "/documents/library",
  "/documents/requests",
  "/signature",
  "/signature/templates",
] as const;

export const PLATFORM_ROUTES = [
  "/booking",
  "/support",
  "/portals",
  "/reports",
  "/analytics",
  "/resources",
  "/calculator",
  "/notifications",
  "/journeys",
  "/time-tracking",
  "/rules",
  "/users",
  "/work-queue",
  "/automations",
  "/smart-link/templates",
] as const;

export const SETTINGS_ROUTES = [
  "/settings",
  "/settings/organization",
  "/settings/organization/company-profile",
  "/settings/my-preferences",
  "/settings/notifications/in-app-notifications",
] as const;
